apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fiap-fase-5
  labels: 
     app: fiap-fase-5
spec:
  selector:
    matchLabels:
      app: fiap-fase-5
      version: v01
  template:
    metadata:
      labels:
        app: fiap-fase-5
        version: v01
    spec:
      serviceAccountName: frames-video-sa
      imagePullSecrets: 
        - name: docker-auth
      restartPolicy: Always
      containers:
      - name: fiap-fase-5
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env: 
        - name: "ASPNETCORE_ENVIROMENT"
          value: "Development"